### ISSUE TITLE
Update for game versions 1.12.3/1.12.4

### ISSUE THREAD

**Issue by Kulberson** [ClayAmore/ER-Save-Editor#56]
Editor update to version 1.12.3 and opening and latest game version in the editor will result in an instant crash

**Comment by yesdog96** [comment]
This is a known issue. Some people have forked and did a hotfix if you look through some of the previous threads, though!

**Comment by Kulberson** [comment]
yea idk if im just looking in the wrong places but it crashes instantly when trying to load a PC or PS4 save

**Comment by renatopontes** [comment]
I had this problem today and did some digging. While reading the save file, the code was reading some insanely large value for the projectile_count of a character and then went out of bounds in the next for loop:

```rust
// Distinct Projectile Count
equip_projectile_data.projectile_count = br.read_i32()?; // was reading something like 16980419

// Quick slot items
for _i in 0..equip_projectile_data.projectile_count { // obviously crashed
    equip_projectile_data.projectiles.push(EquipProjectile::read(br)?);
}
```

After some investigation, my theory is that the game only updates the character data in the save file when that character has been loaded after the update.
So, what fixed it for me was **opening the game and then loading each character that I hadn't used since the DLC update**. Upon loading, these characters receive the new gesture and get a tutorial pop up about the new inventory tab.
After that, the code was able to load the file correctly instead of panicking.

(tested on master version at 014107f0, not on release 0.0.21)

**Comment by ClayAmore** [comment]
Yeah it's the offsets being off. Things changed with the DLC. I am working on a new release and it seems like there's multiple forks that have already hot fixed these issues.
